language: python
python:
  - "3.4"
  - "3.5"
os: linux

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ `which conda` ]]; then echo 'Conda installation successful'; else exit 1; fi
  - conda update --yes conda
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION pip wheel nose
  - source activate testenv
  - conda install --yes gcc
  - echo "Using GCC at "`which gcc`
  - export CC=`which gcc`

install:
  - pip install coverage pep8 python-coveralls
  # Inverse grep allows comments in requirements file
  - cat requirements.txt | grep -v '#' | xargs -n 1 -L 1 pip install
  - cat optional-requirements.txt | grep -v '#' | xargs -n 1 -L 1 pip install
  # Install auto-sklearn
  - curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
  - pip install auto-sklearn==0.1.2
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests -sv --with-coverage --cover-package=hpolib
after_success:
  - coveralls
